INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1001,2, NULL,  'Afghanistan', 'Afghanistan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1002,2, NULL,  'Albania', 'Albania', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1003,2, NULL,  'Algeria', 'Algeria', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1004,2, NULL,  'American Samoa', 'American Samoa', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1005,2, NULL,  'Andorra', 'Andorra', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1006,2, NULL,  'Angola', 'Angola', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1007,2, NULL,  'Anguilla', 'Anguilla', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1008,2, NULL,  'Antarctica', 'Antarctica', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1009,2, NULL,  'Antigua And Barbuda', 'Antigua And Barbuda', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1010,2, NULL,  'Argentina', 'Argentina', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1011,2, NULL,  'Armenia', 'Armenia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1012,2, NULL,  'Aruba', 'Aruba', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1013,2, NULL,  'Australia', 'Australia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1014,2, NULL,  'Austria', 'Austria', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1015,2, NULL,  'Azerbaijan', 'Azerbaijan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1016,2, NULL,  'Bahamas The', 'Bahamas The', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1017,2, NULL,  'Bahrain', 'Bahrain', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1018,2, NULL,  'Bangladesh', 'Bangladesh', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1019,2, NULL,  'Barbados', 'Barbados', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1020,2, NULL,  'Belarus', 'Belarus', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1021,2, NULL,  'Belgium', 'Belgium', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1022,2, NULL,  'Belize', 'Belize', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1023,2, NULL,  'Benin', 'Benin', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1024,2, NULL,  'Bermuda', 'Bermuda', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1025,2, NULL,  'Bhutan', 'Bhutan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1026,2, NULL,  'Bolivia', 'Bolivia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1027,2, NULL,  'Bosnia and Herzegovina', 'Bosnia and Herzegovina', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1028,2, NULL,  'Botswana', 'Botswana', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1029,2, NULL,  'Bouvet Island', 'Bouvet Island', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1030,2, NULL,  'Brazil', 'Brazil', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1031,2, NULL,  'British Indian Ocean Territory', 'British Indian Ocean Territory', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1032,2, NULL,  'Brunei', 'Brunei', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1033,2, NULL,  'Bulgaria', 'Bulgaria', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1034,2, NULL,  'Burkina Faso', 'Burkina Faso', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1035,2, NULL,  'Burundi', 'Burundi', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1036,2, NULL,  'Cambodia', 'Cambodia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1037,2, NULL,  'Cameroon', 'Cameroon', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1038,2, NULL,  'Canada', 'Canada', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1039,2, NULL,  'Cape Verde', 'Cape Verde', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1040,2, NULL,  'Cayman Islands', 'Cayman Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1041,2, NULL,  'Central African Republic', 'Central African Republic', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1042,2, NULL,  'Chad', 'Chad', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1043,2, NULL,  'Chile', 'Chile', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1044,2, NULL,  'China', 'China', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1045,2, NULL,  'Christmas Island', 'Christmas Island', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1046,2, NULL,  'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1047,2, NULL,  'Colombia', 'Colombia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1048,2, NULL,  'Comoros', 'Comoros', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1049,2, NULL,  'Congo', 'Congo', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1050,2, NULL,  'Congo The Democratic Republic Of The', 'Congo The Democratic Republic Of The', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1051,2, NULL,  'Cook Islands', 'Cook Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1052,2, NULL,  'Costa Rica', 'Costa Rica', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1053,2, NULL,  'Cote D''Ivoire (Ivory Coast)', 'Cote D''Ivoire (Ivory Coast)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1054,2, NULL,  'Croatia (Hrvatska)', 'Croatia (Hrvatska)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1055,2, NULL,  'Cuba', 'Cuba', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1056,2, NULL,  'Cyprus', 'Cyprus', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1057,2, NULL,  'Czech Republic', 'Czech Republic', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1058,2, NULL,  'Denmark', 'Denmark', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1059,2, NULL,  'Djibouti', 'Djibouti', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1060,2, NULL,  'Dominica', 'Dominica', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1061,2, NULL,  'Dominican Republic', 'Dominican Republic', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1062,2, NULL,  'East Timor', 'East Timor', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1063,2, NULL,  'Ecuador', 'Ecuador', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1064,2, NULL,  'Egypt', 'Egypt', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1065,2, NULL,  'El Salvador', 'El Salvador', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1066,2, NULL,  'Equatorial Guinea', 'Equatorial Guinea', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1067,2, NULL,  'Eritrea', 'Eritrea', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1068,2, NULL,  'Estonia', 'Estonia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1069,2, NULL,  'Ethiopia', 'Ethiopia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1070,2, NULL,  'External Territories of Australia', 'External Territories of Australia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1071,2, NULL,  'Falkland Islands', 'Falkland Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1072,2, NULL,  'Faroe Islands', 'Faroe Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1073,2, NULL,  'Fiji Islands', 'Fiji Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1074,2, NULL,  'Finland', 'Finland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1075,2, NULL,  'France', 'France', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1076,2, NULL,  'French Guiana', 'French Guiana', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1077,2, NULL,  'French Polynesia', 'French Polynesia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1078,2, NULL,  'French Southern Territories', 'French Southern Territories', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1079,2, NULL,  'Gabon', 'Gabon', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1080,2, NULL,  'Gambia The', 'Gambia The', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1081,2, NULL,  'Georgia', 'Georgia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1082,2, NULL,  'Germany', 'Germany', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1083,2, NULL,  'Ghana', 'Ghana', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1084,2, NULL,  'Gibraltar', 'Gibraltar', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1085,2, NULL,  'Greece', 'Greece', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1086,2, NULL,  'Greenland', 'Greenland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1087,2, NULL,  'Grenada', 'Grenada', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1088,2, NULL,  'Guadeloupe', 'Guadeloupe', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1089,2, NULL,  'Guam', 'Guam', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1090,2, NULL,  'Guatemala', 'Guatemala', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1091,2, NULL,  'Guernsey and Alderney', 'Guernsey and Alderney', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1092,2, NULL,  'Guinea', 'Guinea', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1093,2, NULL,  'Guinea-Bissau', 'Guinea-Bissau', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1094,2, NULL,  'Guyana', 'Guyana', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1095,2, NULL,  'Haiti', 'Haiti', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1096,2, NULL,  'Heard and McDonald Islands', 'Heard and McDonald Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1097,2, NULL,  'Honduras', 'Honduras', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1098,2, NULL,  'Hong Kong S.A.R.', 'Hong Kong S.A.R.', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1099,2, NULL,  'Hungary', 'Hungary', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1100,2, NULL,  'Iceland', 'Iceland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1101,2, NULL,  'India', 'India', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1102,2, NULL,  'Indonesia', 'Indonesia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1103,2, NULL,  'Iran', 'Iran', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1104,2, NULL,  'Iraq', 'Iraq', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1105,2, NULL,  'Ireland', 'Ireland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1106,2, NULL,  'Israel', 'Israel', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1107,2, NULL,  'Italy', 'Italy', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1108,2, NULL,  'Jamaica', 'Jamaica', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1109,2, NULL,  'Japan', 'Japan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1110,2, NULL,  'Jersey', 'Jersey', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1111,2, NULL,  'Jordan', 'Jordan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1112,2, NULL,  'Kazakhstan', 'Kazakhstan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1113,2, NULL,  'Kenya', 'Kenya', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1114,2, NULL,  'Kiribati', 'Kiribati', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1115,2, NULL,  'Korea North', 'Korea North', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1116,2, NULL,  'Korea South', 'Korea South', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1117,2, NULL,  'Kuwait', 'Kuwait', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1118,2, NULL,  'Kyrgyzstan', 'Kyrgyzstan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1119,2, NULL,  'Laos', 'Laos', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1120,2, NULL,  'Latvia', 'Latvia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1121,2, NULL,  'Lebanon', 'Lebanon', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1122,2, NULL,  'Lesotho', 'Lesotho', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1123,2, NULL,  'Liberia', 'Liberia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1124,2, NULL,  'Libya', 'Libya', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1125,2, NULL,  'Liechtenstein', 'Liechtenstein', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1126,2, NULL,  'Lithuania', 'Lithuania', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1127,2, NULL,  'Luxembourg', 'Luxembourg', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1128,2, NULL,  'Macau S.A.R.', 'Macau S.A.R.', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1129,2, NULL,  'Macedonia', 'Macedonia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1130,2, NULL,  'Madagascar', 'Madagascar', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1131,2, NULL,  'Malawi', 'Malawi', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1132,2, NULL,  'Malaysia', 'Malaysia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1133,2, NULL,  'Maldives', 'Maldives', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1134,2, NULL,  'Mali', 'Mali', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1135,2, NULL,  'Malta', 'Malta', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1136,2, NULL,  'Man (Isle of)', 'Man (Isle of)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1137,2, NULL,  'Marshall Islands', 'Marshall Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1138,2, NULL,  'Martinique', 'Martinique', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1139,2, NULL,  'Mauritania', 'Mauritania', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1140,2, NULL,  'Mauritius', 'Mauritius', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1141,2, NULL,  'Mayotte', 'Mayotte', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1142,2, NULL,  'Mexico', 'Mexico', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1143,2, NULL,  'Micronesia', 'Micronesia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1144,2, NULL,  'Moldova', 'Moldova', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1145,2, NULL,  'Monaco', 'Monaco', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1146,2, NULL,  'Mongolia', 'Mongolia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1147,2, NULL,  'Montserrat', 'Montserrat', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1148,2, NULL,  'Morocco', 'Morocco', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1149,2, NULL,  'Mozambique', 'Mozambique', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1150,2, NULL,  'Myanmar', 'Myanmar', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1151,2, NULL,  'Namibia', 'Namibia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1152,2, NULL,  'Nauru', 'Nauru', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1153,2, NULL,  'Nepal', 'Nepal', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1154,2, NULL,  'Netherlands Antilles', 'Netherlands Antilles', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1155,2, NULL,  'Netherlands The', 'Netherlands The', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1156,2, NULL,  'New Caledonia', 'New Caledonia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1157,2, NULL,  'New Zealand', 'New Zealand', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1158,2, NULL,  'Nicaragua', 'Nicaragua', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1159,2, NULL,  'Niger', 'Niger', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1160,2, NULL,  'Nigeria', 'Nigeria', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1161,2, NULL,  'Niue', 'Niue', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1162,2, NULL,  'Norfolk Island', 'Norfolk Island', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1163,2, NULL,  'Northern Mariana Islands', 'Northern Mariana Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1164,2, NULL,  'Norway', 'Norway', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1165,2, NULL,  'Oman', 'Oman', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1166,2, NULL,  'Pakistan', 'Pakistan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1167,2, NULL,  'Palau', 'Palau', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1168,2, NULL,  'Palestinian Territory Occupied', 'Palestinian Territory Occupied', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1169,2, NULL,  'Panama', 'Panama', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1170,2, NULL,  'Papua new Guinea', 'Papua new Guinea', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1171,2, NULL,  'Paraguay', 'Paraguay', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1172,2, NULL,  'Peru', 'Peru', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1173,2, NULL,  'Philippines', 'Philippines', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1174,2, NULL,  'Pitcairn Island', 'Pitcairn Island', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1175,2, NULL,  'Poland', 'Poland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1176,2, NULL,  'Portugal', 'Portugal', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1177,2, NULL,  'Puerto Rico', 'Puerto Rico', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1178,2, NULL,  'Qatar', 'Qatar', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1179,2, NULL,  'Reunion', 'Reunion', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1180,2, NULL,  'Romania', 'Romania', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1181,2, NULL,  'Russia', 'Russia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1182,2, NULL,  'Rwanda', 'Rwanda', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1183,2, NULL,  'Saint Helena', 'Saint Helena', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1184,2, NULL,  'Saint Kitts And Nevis', 'Saint Kitts And Nevis', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1185,2, NULL,  'Saint Lucia', 'Saint Lucia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1186,2, NULL,  'Saint Pierre and Miquelon', 'Saint Pierre and Miquelon', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1187,2, NULL,  'Saint Vincent And The Grenadines', 'Saint Vincent And The Grenadines', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1188,2, NULL,  'Samoa', 'Samoa', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1189,2, NULL,  'San Marino', 'San Marino', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1190,2, NULL,  'Sao Tome and Principe', 'Sao Tome and Principe', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1191,2, NULL,  'Saudi Arabia', 'Saudi Arabia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1192,2, NULL,  'Senegal', 'Senegal', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1193,2, NULL,  'Serbia', 'Serbia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1194,2, NULL,  'Seychelles', 'Seychelles', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1195,2, NULL,  'Sierra Leone', 'Sierra Leone', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1196,2, NULL,  'Singapore', 'Singapore', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1197,2, NULL,  'Slovakia', 'Slovakia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1198,2, NULL,  'Slovenia', 'Slovenia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1199,2, NULL,  'Smaller Territories of the UK', 'Smaller Territories of the UK', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1200,2, NULL,  'Solomon Islands', 'Solomon Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1201,2, NULL,  'Somalia', 'Somalia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1202,2, NULL,  'South Africa', 'South Africa', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1203,2, NULL,  'South Georgia', 'South Georgia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1204,2, NULL,  'South Sudan', 'South Sudan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1205,2, NULL,  'Spain', 'Spain', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1206,2, NULL,  'Sri Lanka', 'Sri Lanka', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1207,2, NULL,  'Sudan', 'Sudan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1208,2, NULL,  'Suriname', 'Suriname', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1209,2, NULL,  'Svalbard And Jan Mayen Islands', 'Svalbard And Jan Mayen Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1210,2, NULL,  'Swaziland', 'Swaziland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1211,2, NULL,  'Sweden', 'Sweden', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1212,2, NULL,  'Switzerland', 'Switzerland', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1213,2, NULL,  'Syria', 'Syria', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1214,2, NULL,  'Taiwan', 'Taiwan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1215,2, NULL,  'Tajikistan', 'Tajikistan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1216,2, NULL,  'Tanzania', 'Tanzania', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1217,2, NULL,  'Thailand', 'Thailand', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1218,2, NULL,  'Togo', 'Togo', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1219,2, NULL,  'Tokelau', 'Tokelau', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1220,2, NULL,  'Tonga', 'Tonga', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1221,2, NULL,  'Trinidad And Tobago', 'Trinidad And Tobago', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1222,2, NULL,  'Tunisia', 'Tunisia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1223,2, NULL,  'Turkey', 'Turkey', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1224,2, NULL,  'Turkmenistan', 'Turkmenistan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1225,2, NULL,  'Turks And Caicos Islands', 'Turks And Caicos Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1226,2, NULL,  'Tuvalu', 'Tuvalu', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1227,2, NULL,  'Uganda', 'Uganda', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1228,2, NULL,  'Ukraine', 'Ukraine', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1229,2, NULL,  'United Arab Emirates', 'United Arab Emirates', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1230,2, NULL,  'United Kingdom', 'United Kingdom', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1231,2, NULL,  'United States', 'United States', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1232,2, NULL,  'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1233,2, NULL,  'Uruguay', 'Uruguay', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1234,2, NULL,  'Uzbekistan', 'Uzbekistan', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1235,2, NULL,  'Vanuatu', 'Vanuatu', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1236,2, NULL,  'Vatican City State (Holy See)', 'Vatican City State (Holy See)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1237,2, NULL,  'Venezuela', 'Venezuela', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1238,2, NULL,  'Vietnam', 'Vietnam', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1239,2, NULL,  'Virgin Islands (British)', 'Virgin Islands (British)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1240,2, NULL,  'Virgin Islands (US)', 'Virgin Islands (US)', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1241,2, NULL,  'Wallis And Futuna Islands', 'Wallis And Futuna Islands', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1242,2, NULL,  'Western Sahara', 'Western Sahara', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1243,2, NULL,  'Yemen', 'Yemen', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1244,2, NULL,  'Yugoslavia', 'Yugoslavia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1245,2, NULL,  'Zambia', 'Zambia', 1 )
INSERT INTO [LookUpValues]([Id], [LookUpTypeId],[ParentId],[LookUpValue],[Description],[IsActive]) VALUES(1246,2, NULL,  'Zimbabwe', 'Zimbabwe', 1 )